# Generated by Django 4.2 on 2023-05-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'))),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('categories', models.ManyToManyField(to='SpaApp.category')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'))),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('duration', models.CharField(max_length=150, verbose_name='Длительность услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaApp.category')),
                ('masters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaApp.masters')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
