# Generated by Django 4.2 on 2023-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
